### ISSUE TITLE
Authentication error while using GoogleVision on Raspberry pi 3

### ISSUE THREAD

**Issue by logiclessindian** [DexterInd/GoogleVisionTutorials#1]
Hello, 

I'm getting following error while trying to invoke the python scripts. Can someone help me, please. 

note : I have installed all the necessary packages and also the credential json file is also kept on home dir and updated the .bashrc file.

note 2 : I followed the instructions as mentioned in [ https://www.dexterindustries.com/howto/use-google-cloud-vision-on-the-raspberry-pi/ ]

`pi@rajberry:~/Andy/GoogleVisionTutorials` $ sudo /usr/bin/python3.4 camera-vision-label.py
Traceback (most recent call last):
  File "camera-vision-label.py", line 50, in <module>
    main()
  File "camera-vision-label.py", line 29, in main
    credentials = GoogleCredentials.get_application_default()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 1271, in get_application_default
    return GoogleCredentials._get_implicit_credentials()
  File "/usr/local/lib/python3.4/dist-packages/oauth2client/client.py", line 1261, in _get_implicit_credentials
    raise ApplicationDefaultCredentialsError(ADC_HELP_MSG)
oauth2client.client.ApplicationDefaultCredentialsError: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
pi@rajberry:~/Andy/GoogleVisionTutorials $'

**Comment by heinaungthutrends** [comment]
HI I am also having the same issue
